server:
  port: 8099

spring:
  application:
    name: library-api
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect